#!/bin/bash

SCRIPT_PATH="$(dirname -- "${BASH_SOURCE[0]}")"
JENKINS_HOME="$SCRIPT_PATH/../jenkins_home"

red() {
    echo '\033[1;31m'$1'\033[0m'
}
WHAT=$1
case "$WHAT" in
    save-admin-token|s)
        TOKEN=$(sudo cat $JENKINS_HOME/secrets/initialAdminPassword)
        echo $TOKEN > $JENKINS_HOME/initialAdminPassword
        echo $TOKEN

        ;;
    get-admin-token|g)
        TOKEN=$(cat $JENKINS_HOME/initialAdminPassword)
        echo $TOKEN

        ;;
    clear-jenkins-home|c)
        sudo rm -rf $JENKINS_HOME

        # Create the volume directory before mount to the docker
        # container => so it owned outside the docker container
        mkdir $JENKINS_HOME
        ls -la $JENKINS_HOME

        ;;
    *)
        echo -e "Only the following operations are supported:\n"
        echo -e "admin-token [$(red s)]ave-admin-token, save the admin token in a file that is accessible out of the docker container"
        echo -e "admin-token [$(red g)]et-admin-token, get the admin token, no need for sudo"
        echo -e "admin-token [$(red c)]lear-jenkins-home"
        exit 1
        ;;
esac