#!/bin/bash

SCRIPT_PATH="$(dirname -- "${BASH_SOURCE[0]}")"

sudo rm -rf $SCRIPT_PATH/../jenkins_home

# Create the volume directory before mount to the docker
# container => so it owned outside the docker container
mkdir $SCRIPT_PATH/../jenkins_home